import { passClaims, passExpiry } from './allowance';
import type { CheckoutCreator, Clock, PaymentVerifier, TokenSigner } from './ports';
import type { ErrorCode } from './results';

export const PASS_PRICE_CENTS = 499;
export const PASS_CURRENCY = 'eur';

// Generated by the browser and kept there; a leaked session id alone can't redeem a pass.
const NONCE = /^[A-Za-z0-9_-]{22,64}$/;
const SESSION_ID = /^cs_(test|live)_[A-Za-z0-9]{1,250}$/;

export const isNonce = (v: unknown): v is string => typeof v === 'string' && NONCE.test(v);
export const isSessionId = (v: unknown): v is string => typeof v === 'string' && SESSION_ID.test(v);

export type CheckoutResponse =
  | { readonly code: 'ok'; readonly sessionId: string; readonly url: string }
  | { readonly code: ErrorCode };

export async function startCheckout(
  nonce: string,
  deps: { readonly checkout: CheckoutCreator },
): Promise<CheckoutResponse> {
  try {
    const session = await deps.checkout.create(nonce);
    return { code: 'ok', ...session };
  } catch {
    return { code: 'payment_provider_unavailable' };
  }
}

export interface PassDeps {
  readonly payments: PaymentVerifier;
  readonly signer: TokenSigner;
  readonly clock: Clock;
  readonly priceId: string;
}

export type PassResponse =
  | { readonly code: 'ok'; readonly pass: string; readonly expiresAt: number }
  | { readonly code: ErrorCode };

// Same session and nonce, same pass: the token is derived only from what Stripe returns.
export async function issuePass(
  sessionId: string,
  nonce: string,
  deps: PassDeps,
): Promise<PassResponse> {
  let session;
  try {
    session = await deps.payments.findSession(sessionId);
  } catch {
    return { code: 'payment_provider_unavailable' };
  }
  if (session === null) return { code: 'session_not_found' };
  if (session.clientReferenceId !== nonce) return { code: 'session_mismatch' };
  if (
    session.mode !== 'payment' ||
    session.status !== 'complete' ||
    session.paymentStatus === 'unpaid'
  )
    return { code: 'payment_not_complete' };
  const [line, ...rest] = session.lineItems;
  if (
    session.currency !== PASS_CURRENCY ||
    session.amountSubtotal !== PASS_PRICE_CENTS ||
    line === undefined ||
    rest.length > 0 ||
    line.priceId !== deps.priceId ||
    line.unitAmount !== PASS_PRICE_CENTS ||
    line.quantity !== 1
  )
    return { code: 'price_mismatch' };
  const expiresAt = passExpiry(session.created);
  if (deps.clock.now() >= expiresAt * 1000) return { code: 'pass_expired' };
  return { code: 'ok', pass: deps.signer.sign(passClaims(session.id, expiresAt, 0)), expiresAt };
}
