import { checkAllowance, passClaims, passExpiry, passSessionProblem, readsLeft } from './allowance';
import type {
  CaptchaVerifier,
  CheckoutCreator,
  Clock,
  PaymentVerifier,
  TokenSigner,
} from './ports';
import type { ErrorCode } from './results';
import type { CheckoutReview } from './reviews';

export const PASS_PRICE_CENTS = 499;
export const PASS_CURRENCY = 'eur';

// Generated by the browser and kept there; a leaked session id alone can't redeem a pass.
const NONCE = /^[A-Za-z0-9_-]{22,64}$/;
const SESSION_ID = /^cs_(test|live)_[A-Za-z0-9]{1,250}$/;

export const isNonce = (v: unknown): v is string => typeof v === 'string' && NONCE.test(v);
export const isSessionId = (v: unknown): v is string => typeof v === 'string' && SESSION_ID.test(v);

export type CheckoutResponse =
  | { readonly code: 'ok'; readonly sessionId: string; readonly url: string }
  | { readonly code: ErrorCode };

export async function startCheckout(
  nonce: string,
  captchaToken: string,
  deps: { readonly checkout: CheckoutCreator; readonly captcha: CaptchaVerifier },
  returnTo: CheckoutReview = 'final_pay',
): Promise<CheckoutResponse> {
  if (!(await deps.captcha.verify(captchaToken))) return { code: 'captcha_failed' };
  try {
    const session = await deps.checkout.create(nonce, returnTo);
    return { code: 'ok', ...session };
  } catch {
    return { code: 'payment_provider_unavailable' };
  }
}

export interface PassDeps {
  readonly payments: PaymentVerifier;
  readonly signer: TokenSigner;
  readonly clock: Clock;
  readonly priceId: string;
}

export type PassResponse =
  | {
      readonly code: 'ok';
      readonly pass: string;
      readonly expiresAt: number;
      readonly readsLeft: number;
    }
  | { readonly code: ErrorCode };

// Same session and nonce, same pass; the reads it has left come from Stripe, not the token.
export async function issuePass(
  sessionId: string,
  nonce: string,
  deps: PassDeps,
): Promise<PassResponse> {
  let session;
  try {
    session = await deps.payments.findSession(sessionId);
  } catch {
    return { code: 'payment_provider_unavailable' };
  }
  if (session === null) return { code: 'session_not_found' };
  if (session.clientReferenceId !== nonce) return { code: 'session_mismatch' };
  const [line, ...rest] = session.lineItems;
  if (
    session.currency !== PASS_CURRENCY ||
    session.amountSubtotal !== PASS_PRICE_CENTS ||
    line === undefined ||
    rest.length > 0 ||
    line.priceId !== deps.priceId ||
    line.unitAmount !== PASS_PRICE_CENTS ||
    line.quantity !== 1
  )
    return { code: 'price_mismatch' };
  const problem = passSessionProblem(session, deps.clock.now());
  if (problem !== null) return { code: problem };
  const expiresAt = passExpiry(session.created);
  return {
    code: 'ok',
    pass: deps.signer.sign(passClaims(session.id, expiresAt)),
    expiresAt,
    readsLeft: readsLeft(session),
  };
}

export type VerifyResponse =
  | { readonly code: 'ok'; readonly expiresAt: number; readonly readsLeft: number }
  | { readonly code: ErrorCode };

// A pass verified a moment ago, by the hash of its token, so a page that reloads does not reach
// Stripe every time. Per container: a refund can take this long to withdraw a pass that already
// unlocked the page.
export const VERIFY_MEMO_MS = 60_000;

export interface VerifyMemo {
  get(key: string, nowMs: number): VerifyResponse | null;
  set(key: string, response: VerifyResponse, nowMs: number): void;
}

const MEMO_LIMIT = 500;

export function createVerifyMemo(): VerifyMemo {
  const entries = new Map<string, { response: VerifyResponse; until: number }>();
  return {
    get(key, nowMs) {
      const hit = entries.get(key);
      if (!hit || hit.until <= nowMs) {
        entries.delete(key);
        return null;
      }
      return hit.response;
    },
    set(key, response, nowMs) {
      if (entries.size >= MEMO_LIMIT) entries.clear();
      entries.set(key, { response, until: nowMs + VERIFY_MEMO_MS });
    },
  };
}

// Whether a pass the browser holds still unlocks the detail, the report and the letter: its
// signature and expiry here, then its session in Stripe (refunded, disputed or cancelled). Only a
// successful answer is remembered. A pass this API signed whose session Stripe doesn't find is
// `pass_unconfirmed`, never `pass_invalid`: a rotated key, a test/live mix-up or an outage must not
// make the browser drop a paid pass. Only a bad signature, an expired token, or Stripe stating a
// refund, a dispute, a cancellation or no payment says the pass is gone.
export async function verifyPass(
  token: string,
  deps: PassDeps & { readonly memo: VerifyMemo; readonly hash: (token: string) => string },
): Promise<VerifyResponse> {
  const now = deps.clock.now();
  const check = checkAllowance({ type: 'pass', token }, deps.signer, now);
  if (!check.ok) return { code: check.code };
  if (check.type !== 'pass') return { code: 'pass_invalid' };
  const key = deps.hash(token);
  const remembered = deps.memo.get(key, now);
  if (remembered) return remembered;
  let session;
  try {
    session = await deps.payments.findSession(check.sessionId);
  } catch {
    return { code: 'payment_provider_unavailable' };
  }
  if (session === null) return { code: 'pass_unconfirmed' };
  const problem = passSessionProblem(session, now);
  if (problem === 'payment_not_complete') return { code: 'pass_invalid' };
  if (problem !== null) return { code: problem };
  const response: VerifyResponse = {
    code: 'ok',
    expiresAt: passExpiry(session.created),
    readsLeft: readsLeft(session),
  };
  deps.memo.set(key, response, now);
  return response;
}
