import { parseDate } from '../../../src/engine/date';
import {
  INFO_ELEMENTS,
  type EmploymentInput,
  type Finding,
} from '../../../src/engine/employment/types';

// A synthetic full-time permanent contract; tests override what they check.
export const contract = (change: Partial<EmploymentInput> = {}): EmploymentInput => ({
  relationship: 'common',
  viaTempAgency: false,
  relief: false,
  under18: false,
  writtenContract: true,
  startDate: parseDate('2024-03-01'),
  endDate: null,
  signedOn: parseDate('2024-02-26'),
  modality: 'permanent',
  extensions: 0,
  causeStated: null,
  circumstancesStated: null,
  replacedPersonNamed: null,
  replacementCauseStated: null,
  discontinuous: null,
  training: null,
  salary: {
    amount: 1500,
    period: 'month',
    payments: 14,
    prorated: false,
    breakdown: [{ kind: 'base', amount: 1500 }],
    inKind: null,
  },
  contractHours: { weekly: 40, annual: null },
  fullTimeHours: null,
  agreement: {
    named: false,
    categoryAnnualSalary: null,
    annualHours: null,
    holidayDays: null,
    trialMonths: null,
  },
  payslips: [],
  trial: { amount: 2, unit: 'months' },
  technical: false,
  smallCompany: false,
  sameDutiesBefore: false,
  afterTraining: false,
  schedule: [{ day: 1, slots: [{ from: '09:00', to: '17:00' }] }],
  shifts: false,
  nightWorker: false,
  irregular: false,
  overtimeAgreed: null,
  partTime: null,
  remoteShare: null,
  realWeeklyHours: null,
  holidays: { days: 30, unit: 'calendar', workDaysPerWeek: 5, includedInSalary: false },
  extraPays: { count: 2, prorated: false },
  clauses: [],
  info: Object.fromEntries(INFO_ELEMENTS.map((e) => [e, 'present'])) as EmploymentInput['info'],
  history: null,
  offer: null,
  ...change,
});

export const finding = (change: Partial<Finding> = {}): Finding => ({
  id: 'trial_limits',
  item: 'trial_period',
  status: 'within_limit',
  amount: null,
  calculation: [],
  sources: [],
  basedOnYourAnswer: false,
  agreementMaySetOther: false,
  literal: null,
  ...change,
});
