import { describe, expect, it } from 'vitest';
import { hasSpecialCategory } from '../src/domain/special-categories';

describe('hasSpecialCategory', () => {
  it.each([
    'COMPLEMENTO IT',
    'COMPL. I.T. EMPRESA',
    'Prestación por incapacidad temporal',
    'Baja por enfermedad común',
    'Accidente de trabajo',
    'PRESTACIÓN MATERNIDAD',
    'Permiso de paternidad',
    'Nacimiento y cuidado de menor',
    'Hora de lactancia',
    'Riesgo durante el embarazo',
    'CUOTA SINDICAL',
    'Liberado del sindicato',
    'Afiliado a CCOO',
    'Delegado de UGT',
    'CC.OO.',
    'Discapacidad del 33 %',
    'Grado de minusvalía',
    'Diversidad funcional',
    'REGULARIZACIÓN EMBARGO',
    'Pensión alimenticia',
    'Baixa per malaltia',
    'gaixotasun arrunta',
    'SALUD LABORAL',
    'IT',
    'I.T.',
    'Compl. IT',
    'IT EC',
    'PRESTACIÓN I.T. PAGO DELEGADO',
    'Enfermedades comunes',
    'Accidentes laborales',
    'EMBARGOS',
    'Sindicatos firmantes',
    'Afiliados',
    'Persona discapacitada',
    'Inc. temporal',
    'CUOTA SIND.',
    'Emb. judicial',
    'Compl. AT',
    'AT',
    'Retención judicial',
    'Permiso nacimiento',
    'Incapacitat temporal',
    'Treballador afiliat',
    'Persona amb discapacitat',
    'EMBARGAMENT DE SALARI',
    'Incapacidade temporal',
    'Enfermidade común',
    'Permiso de maternidade',
    'Permiso de paternidade',
    'Persoa con discapacidade',
    'Aldi baterako ezintasuna',
    'Gaixotasun arruntagatik',
    'Amatasun baimena',
    'Aitatasunagatiko baimena',
    'Sindikatuko kuota',
    'Desgaitasunaren ehunekoa',
    'Soldataren bahiketa',
    'Vigilancia de la salud',
  ])('finds one in «%s»', (text) => {
    expect(hasSpecialCategory(text)).toBe(true);
  });

  it.each([
    'Plus de transporte',
    'Complemento de nocturnidad',
    'PLUS CONVENIO',
    'Salario base',
    'Horas extraordinarias',
    'Antigüedad',
    'Paga extra de verano',
    'Dietas y kilometraje',
    'Itinerario formativo',
    'Oficial de primera de mantenimiento',
    'Campaña de verano en el centro de Bilbao',
    'Convenio colectivo de oficinas y despachos',
    'Embarque de mercancías',
    'it is a fixed-term contract',
    'Lan-kontratu mugagabea',
    'Sin embargo, la jornada podrá distribuirse de forma irregular.',
    'Afiliación a la Seguridad Social',
    'La empresa da de alta al trabajador, afiliado a la Seguridad Social',
    'Técnico IT',
    'Responsable de IT y sistemas',
    'Plus de atención al cliente',
  ])('finds nothing in «%s»', (text) => {
    expect(hasSpecialCategory(text)).toBe(false);
  });
});
