// Subsets the site's sans and serif faces for the PDFs the browser builds (report and letter):
// Latin-1 plus the punctuation the dictionary uses, at each font's default instance.
// Run with `node scripts/pdf-fonts.mjs` and commit src/documents/fonts/.
import { readFileSync, writeFileSync } from 'node:fs';
import { create } from 'fontkit';
import { decompress } from 'wawoff2';

const FACES = [
  {
    name: 'sans',
    postscript: 'GolosText-Regular',
    file: '@fontsource-variable/golos-text/files/golos-text-latin-wght-normal.woff2',
  },
  {
    name: 'serif',
    postscript: 'SourceSerif4-Regular',
    file: '@fontsource-variable/source-serif-4/files/source-serif-4-latin-opsz-normal.woff2',
  },
];

const range = (a, b) => Array.from({ length: b - a + 1 }, (_, i) => a + i);
const CODEPOINTS = [
  ...range(0x20, 0x7e),
  ...range(0xa1, 0xff),
  ...[0x2018, 0x2019, 0x201c, 0x201d, 0x2013, 0x2014, 0x2026, 0x20ac, 0x2022, 0x2212, 0x2248],
];

for (const face of FACES) {
  const font = create(Buffer.from(await decompress(readFileSync(`node_modules/${face.file}`))));
  const subset = font.createSubset();
  const glyphs = {};
  for (const cp of CODEPOINTS) {
    if (!font.hasGlyphForCodePoint(cp)) continue;
    const glyph = font.glyphForCodePoint(cp);
    const gid = subset.includeGlyph(glyph);
    glyphs[cp] = [gid, glyph.advanceWidth];
  }
  const data = Buffer.from(subset.encode()).toString('base64');
  const { minX, minY, maxX, maxY } = font.bbox;
  const source = [
    "// Generated by scripts/pdf-fonts.mjs from the site's own font. Do not edit.",
    "import type { EmbeddedFont } from '../pdf-writer';",
    '',
    `export const ${face.name}: EmbeddedFont = {`,
    `  name: '${face.postscript}',`,
    `  unitsPerEm: ${font.unitsPerEm},`,
    `  ascent: ${font.ascent},`,
    `  descent: ${font.descent},`,
    `  capHeight: ${font.capHeight},`,
    `  bbox: [${minX}, ${minY}, ${maxX}, ${maxY}],`,
    `  glyphs: ${JSON.stringify(glyphs)},`,
    `  data: '${data}',`,
    '};',
    '',
  ].join('\n');
  writeFileSync(`src/documents/fonts/${face.name}.ts`, source);
  console.log(face.name, Object.keys(glyphs).length, 'glyphs', data.length, 'base64 bytes');
}
